### ISSUE TITLE
[issue] : [todo]

### ISSUE THREAD

**Issue by ysh4296** [ysh4296/BigMacExchange#1]
- [x] add change locale
- [x] add github link
- [x] add google adds
- [x] add robots.txt
- [x] add e2e test
- [x] add sitemap
- [x] improve output UI description

**Comment by ysh4296** [comment]
job done
